name: Deploy EMS App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install frontend dependencies
      run: |
        cd iot-dashboard-frontend
        npm install

    - name: Build React
      run: |
        cd iot-dashboard-frontend
        npm run build

    - name: Upload Frontend Build
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "iot-dashboard-frontend/build/*"
        target: "/var/www/ems/"

    - name: Deploy Backend
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/technotech

          git fetch origin
          git reset --hard origin/master

          docker-compose up -d --build

          docker system prune -f