name: Deploy EMS App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ubuntu/technotech/
          git pull origin master
          
          echo "Installing backend dependencies"
          cd server
          npm install

          echo "Building frontend"
          cd ../iot-dashboard-frontend
          npm install
          npm run build

          echo "Restarting server"
          pm2 restart all